quarkus:
  log:
    category:
      "org.apache.pdfbox":
        level: ERROR
      "org.atmosphere":
        level: WARN
      "io.quarkiverse.wiremock":
        level: WARN
      "com.vaadin.flow.server.frontend":
        level: WARN
  langchain4j:
    chat-model:
      provider: openai
    embedding-model:
      provider: openai
    openai:
      base-url: http://localhost:11434/v1
      api-key: none
      chat-model:
        model-name: qwen3:30b-a3b
        temperature: 0
      embedding-model:
        model-name: nomic-embed-text
    qdrant:
      devservices:
        collection:
          vector-params:
            size: 768
            distance: Cosine
      default-store-enabled: false
      naive:
        collection-name: naive
        collection:
          name: naive
      docling-naive:
        collection-name: docling_naive_chunk
        collection:
          name: docling_naive_chunk
      docling-hybrid:
        collection-name: docling_hybrid_chunk
        collection:
          name: docling_hybrid_chunk

"%dev":
  quarkus:
    langchain4j:
      chat-model:
        provider: ollama
      embedding-model:
        provider: ollama
      timeout: 60s
      ollama:
        timeout: 60s
        chat-model:
          model-id: qwen3:30b-a3b
        embedding-model:
          model-id: nomic-embed-text

"%test":
  quarkus:
    langchain4j:
      chat-model:
        provider: openai
      embedding-model:
        provider: ollama
      timeout: 60s
      openai:
        base-url: http://localhost:${quarkus.wiremock.devservices.port}/v1
        api-key: none
        chat-model:
          model-name: stub
          temperature: 0
      ollama:
        timeout: 60s
        chat-model:
          model-id: qwen3:30b-a3b
        embedding-model:
          model-id: nomic-embed-text
