name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: "workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}, pr = ${{ github.event.pull_request.id }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    services:
      ollama:
        image: ollama/ollama
        ports:
          - 11434:11434
        options: --name ollama --rm
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '25'
          cache: maven
      - name: Pull Ollama models
        run: |
          docker exec ollama bash -c "\
            ollama pull qwen3:1.7b && \
            ollama pull nomic-embed-text && \
            ollama ls"
      - name: Build and test
        run: |
          ./mvnw -B verify \
            -Dquarkus.langchain4j.ollama.devservices.enabled=false \
            -Dquarkus.langchain4j.ollama.base-url=http://localhost:11434 \
            -Dquarkus.langchain4j.ollama.chat-model.model-id=qwen3:1.7b \
            -Dquarkus.langchain4j.ollama.timeout=120s \
            -Ddemo.rag.ingestion.parallel=false \
            -Duse.wiremock.docling=true \
            -Drun.planted-questions=true
