name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    services:
      ollama:
        image: ollama/ollama
        ports:
          - 11434:11434
        options: --name ollama --rm
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '25'
          cache: maven
      - name: Pull Ollama models
        run: |
          docker exec ollama bash -c "\
          ollama pull qwen3:4b && \
          ollama pull nomic-embed-text && \
          ollama ls"
      - name: Build and test
        run: ./mvnw -B verify -Dquarkus.langchain4j.ollama.chat-model.model-id=qwen3:4b
